# utils/export_aliases.py
import json
# app/feature_aliases.py
FEATURE_ALIASES = {
    # --- Core external scores & personal info ---
    "EXT_SOURCE_1": "External Credit Score Source 1",
    "EXT_SOURCE_2": "External Credit Score Source 2",
    "EXT_SOURCE_3": "External Credit Score Source 3",
    "DAYS_BIRTH": "Age (in days)",
    "AGE": "Age (years)",
    "DAYS_EMPLOYED": "Employment Duration (days)",
    "OWN_CAR_AGE": "Car Ownership Age (years)",
    "CNT_CHILDREN": "Number of Children",
    "CNT_FAM_MEMBERS": "Family Members Count",
    "AMT_INCOME_TOTAL": "Total Annual Income",
    "CODE_GENDER": "Gender",
    "CODE_GENDER_M": "Gender-Male",
    # --- Current application IDs / basic amounts ---
    "SK_ID_CURR": "Customer ID",
    "AMT_CREDIT": "Loan Amount Requested",
    "AMT_ANNUITY": "Monthly Annuity Amount",
    "AMT_GOODS_PRICE": "Goods / Asset Price",
    # --- Application meta & time fields ---
    "DAYS_ID_PUBLISH": "Days Since ID Published",
    "DAYS_REGISTRATION": "Days Since Registration",
    "DAYS_LAST_PHONE_CHANGE": "Days Since Last Phone Change",
    "HOUR_APPR_PROCESS_START": "Application Start Hour",
    "WEEKDAY_APPR_PROCESS_START_FRIDAY": "Application Weekday – Friday",
    "WEEKDAY_APPR_PROCESS_START_MONDAY_y": "Application Weekday – Monday",
    "WEEKDAY_APPR_PROCESS_START_TUESDAY_y": "Application Weekday – Tuesday",
    "WEEKDAY_APPR_PROCESS_START_WEDNESDAY_y": "Application Weekday – Wednesday",
    "WEEKDAY_APPR_PROCESS_START_THURSDAY_y": "Application Weekday – Thursday",
    "WEEKDAY_APPR_PROCESS_START_SATURDAY_y": "Application Weekday – Saturday",
    "WEEKDAY_APPR_PROCESS_START_SUNDAY_y": "Application Weekday – Sunday",
    # --- Contract types / statuses ---
    "NAME_CONTRACT_TYPE": "Type of Loan",
    "NAME_CONTRACT_TYPE_Cash loans": "Contract Type – Cash Loan",
    "NAME_CONTRACT_TYPE_Consumer loans": "Contract Type – Consumer Loan",
    "NAME_CONTRACT_TYPE_Revolving loans": "Contract Type – Revolving Loan",
    "NAME_CONTRACT_STATUS_Active_x": "Contract Status – Active",
    "NAME_CONTRACT_STATUS_Completed_x": "Contract Status – Completed",
    "NAME_CONTRACT_STATUS_Canceled_x": "Contract Status – Canceled",
    "NAME_CONTRACT_STATUS_Returned to the store": "Contract Status – Returned to Store",
    "NAME_CONTRACT_STATUS_Signed_x": "Contract Status – Signed",
    "NAME_CONTRACT_STATUS_Approved_x": "Contract Status – Approved",
    "NAME_CONTRACT_STATUS_Refused_x": "Contract Status – Refused",
    "NAME_CONTRACT_STATUS_Unused offer": "Contract Status – Unused Offer",
    # --- Education, client type, yield group, payment type ---
    "NAME_EDUCATION_TYPE": "Education Level",
    "NAME_EDUCATION_TYPE_Higher education": "Education – Higher",
    "NAME_EDUCATION_TYPE_Secondary / secondary special": "Education – Secondary / Special",
    "NAME_CLIENT_TYPE_New": "Client Type – New",
    "NAME_CLIENT_TYPE_Repeater": "Client Type – Repeater",
    "NAME_CLIENT_TYPE_Refreshed": "Client Type – Refreshed",
    "NAME_PAYMENT_TYPE_Cash through the bank": "Payment Type – Cash via Bank",
    "NAME_PAYMENT_TYPE_XNA": "Payment Type – Unknown",
    "NAME_YIELD_GROUP_high": "Yield Group – High",
    "NAME_YIELD_GROUP_low_action": "Yield Group – Low (Action)",
    "NAME_YIELD_GROUP_low_normal": "Yield Group – Low (Normal)",
    "NAME_YIELD_GROUP_middle": "Yield Group – Middle",
    "NAME_YIELD_GROUP_XNA": "Yield Group – Unknown",
    # --- Portfolio & product info ---
    "NAME_PORTFOLIO_Cash": "Portfolio – Cash",
    "NAME_PORTFOLIO_Cards": "Portfolio – Cards",
    "NAME_PORTFOLIO_POS": "Portfolio – POS",
    "NAME_PORTFOLIO_XNA": "Portfolio – Unknown",
    "NAME_PRODUCT_TYPE_walk-in": "Product Type – Walk‑in",
    "NAME_PRODUCT_TYPE_x-sell": "Product Type – Cross‑sell",
    "NAME_PRODUCT_TYPE_XNA": "Product Type – Unknown",
    # --- Suite / accommodation ---
    "NAME_TYPE_SUITE_Family_y": "Accommodation Suite – Family",
    "NAME_TYPE_SUITE_Children": "Accommodation Suite – With Children",
    "NAME_TYPE_SUITE_Spouse, partner_y": "Accommodation Suite – Spouse/Partner",
    "NAME_TYPE_SUITE_Unaccompanied_y": "Accommodation Suite – Unaccompanied",
    "NAME_TYPE_SUITE_Other_B_y": "Accommodation Suite – Other",
    # --- Goods & seller / industry ---
    "NAME_GOODS_CATEGORY_Audio/Video": "Goods Category – Audio/Video",
    "NAME_GOODS_CATEGORY_Computers": "Goods Category – Computers",
    "NAME_GOODS_CATEGORY_Consumer Electronics": "Goods Category – Consumer Electronics",
    "NAME_GOODS_CATEGORY_Furniture": "Goods Category – Furniture",
    "NAME_GOODS_CATEGORY_Mobile": "Goods Category – Mobile",
    "NAME_GOODS_CATEGORY_Photo / Cinema Equipment": "Goods Category – Photo/Cinema Equipment",
    "NAME_GOODS_CATEGORY_XNA": "Goods Category – Unknown",
    "NAME_SELLER_INDUSTRY_Connectivity": "Seller Industry – Connectivity",
    "NAME_SELLER_INDUSTRY_Consumer electronics": "Seller Industry – Consumer Electronics",
    "NAME_SELLER_INDUSTRY_XNA": "Seller Industry – Unknown",
    # --- Combination tags ---
    "PRODUCT_COMBINATION_Cash": "Product Combination – Cash",
    "PRODUCT_COMBINATION_Cash X-Sell: low": "Product Combination – Cash Cross‑sell (Low)",
    "PRODUCT_COMBINATION_POS mobile with interest": "Product Combination – POS Mobile (Interest)",
    # --- Channel types ---
    "CHANNEL_TYPE_Country-wide": "Channel Type – Country‑wide",
    "CHANNEL_TYPE_Credit and cash offices": "Channel Type – Credit & Cash Offices",
    "CHANNEL_TYPE_AP+ (Cash loan)": "Channel Type – AP+ (Cash Loan)",
    "CHANNEL_TYPE_Regional / Local": "Channel Type – Regional / Local",
    "CHANNEL_TYPE_Contact center": "Channel Type – Contact Center",
    "CHANNEL_TYPE_Stone": "Channel Type – Stone",
    # --- Credit bureau aggregates (BUREAU_) ---
    "BUREAU_DAYS_CREDIT_MAX": "Days Since Credit (Max)",
    "BUREAU_DAYS_CREDIT_MEAN": "Days Since Credit (Mean)",
    "BUREAU_DAYS_CREDIT_MIN": "Days Since Credit (Min)",
    "BUREAU_DAYS_CREDIT_ENDDATE_MEAN": "Days Until Credit End (Mean)",
    "BUREAU_DAYS_CREDIT_ENDDATE_MAX": "Days Until Credit End (Max)",
    "BUREAU_DAYS_CREDIT_ENDDATE_MIN": "Days Until Credit End (Min)",
    "BUREAU_DAYS_CREDIT_UPDATE_MEAN": "Days Since Credit Update (Mean)",
    "BUREAU_DAYS_CREDIT_UPDATE_MAX": "Days Since Credit Update (Max)",
    "BUREAU_DAYS_CREDIT_UPDATE_MIN": "Days Since Credit Update (Min)",
    "BUREAU_DAYS_ENDDATE_FACT_MEAN": "Days Since Credit End (Mean)",
    "BUREAU_DAYS_ENDDATE_FACT_MAX": "Days Since Credit End (Max)",
    "BUREAU_DAYS_ENDDATE_FACT_MIN": "Days Since Credit End (Min)",
    "BUREAU_AMT_CREDIT_SUM_SUM": "Total Credit Amount (Sum)",
    "BUREAU_AMT_CREDIT_SUM_MEAN": "Total Credit Amount (Mean)",
    "BUREAU_AMT_CREDIT_SUM_MAX": "Total Credit Amount (Max)",
    "BUREAU_AMT_CREDIT_SUM_DEBT_MEAN": "Credit Debt (Mean)",
    "BUREAU_AMT_CREDIT_SUM_DEBT_SUM": "Credit Debt (Sum)",
    "BUREAU_AMT_CREDIT_SUM_DEBT_MAX": "Credit Debt (Max)",
    "BUREAU_AMT_CREDIT_MAX_OVERDUE_MEAN": "Max Overdue Credit (Mean)",
    "BUREAU_AMT_CREDIT_MAX_OVERDUE_MAX": "Max Overdue Credit (Max)",
    "BUREAU_AMT_CREDIT_MAX_OVERDUE_SUM": "Max Overdue Credit (Sum)",
    "BUREAU_AMT_CREDIT_SUM_LIMIT_MEAN": "Credit Limit (Mean)",
    "BUREAU_AMT_CREDIT_SUM_LIMIT_MAX": "Credit Limit (Max)",
    "BUREAU_AMT_CREDIT_SUM_LIMIT_SUM": "Credit Limit (Sum)",
    "BUREAU_AMT_CREDIT_SUM_OVERDUE_MEAN": "Credit Sum Overdue (Mean)",
    "BUREAU_SK_ID_BUREAU_MIN": "Bureau Record ID (Min)",
    "BUREAU_SK_ID_BUREAU_MAX": "Bureau Record ID (Max)",
    "BUREAU_SK_ID_BUREAU_MEAN": "Bureau Record ID (Mean)",
    # --- POS cash balance aggregates (POS_) ---
    "POS_SK_ID_PREV_MEAN": "POS Previous ID (Mean)",
    "POS_SK_ID_PREV_MAX": "POS Previous ID (Max)",
    "POS_SK_ID_PREV_MIN": "POS Previous ID (Min)",
    "POS_CNT_INSTALMENT_FUTURE_MEAN": "Future Instalments Count (Mean)",
    "POS_CNT_INSTALMENT_FUTURE_SUM": "Future Instalments Count (Sum)",
    "POS_CNT_INSTALMENT_FUTURE_MAX": "Future Instalments Count (Max)",
    "POS_CNT_INSTALMENT_MEAN": "Instalment Count (Mean)",
    "POS_CNT_INSTALMENT_SUM": "Instalment Count (Sum)",
    "POS_CNT_INSTALMENT_MAX": "Instalment Count (Max)",
    "POS_MONTHS_BALANCE_MEAN": "POS Months Balance (Mean)",
    "POS_MONTHS_BALANCE_SUM": "POS Months Balance (Sum)",
    "POS_MONTHS_BALANCE_MAX": "POS Months Balance (Max)",
    "POS_SK_DPD_MEAN": "POS Days Past Due (Mean)",
    "POS_SK_DPD_MAX": "POS Days Past Due (Max)",
    "POS_SK_DPD_SUM": "POS Days Past Due (Sum)",
    "POS_SK_DPD_DEF_MEAN": "POS Days Past Due >30 (Mean)",
    "POS_SK_DPD_DEF_MAX": "POS Days Past Due >30 (Max)",
    "POS_SK_DPD_DEF_SUM": "POS Days Past Due >30 (Sum)",
    # --- Previous application aggregates (PREVAPP_) ---
    "PREVAPP_SK_ID_PREV_MAX": "Previous Application ID (Max)",
    "PREVAPP_SK_ID_PREV_MEAN": "Previous Application ID (Mean)",
    "PREVAPP_DAYS_DECISION_MEAN": "Decision Days (Mean)",
    "PREVAPP_DAYS_DECISION_MAX": "Decision Days (Max)",
    "PREVAPP_AMT_ANNUITY_MEAN": "Previous Annuity Amount (Mean)",
    "PREVAPP_AMT_ANNUITY_MAX": "Previous Annuity Amount (Max)",
    "PREVAPP_AMT_ANNUITY_SUM": "Previous Annuity Amount (Sum)",
    "PREVAPP_AMT_CREDIT_MEAN": "Previous Credit Amount (Mean)",
    "PREVAPP_AMT_CREDIT_MAX": "Previous Credit Amount (Max)",
    "PREVAPP_AMT_CREDIT_SUM": "Previous Credit Amount (Sum)",
    "PREVAPP_AMT_APPLICATION_MEAN": "Previous Application Amount (Mean)",
    "PREVAPP_AMT_APPLICATION_MAX": "Previous Application Amount (Max)",
    "PREVAPP_AMT_APPLICATION_SUM": "Previous Application Amount (Sum)",
    "PREVAPP_AMT_GOODS_PRICE_MEAN": "Previous Goods Price (Mean)",
    "PREVAPP_AMT_GOODS_PRICE_MAX": "Previous Goods Price (Max)",
    "PREVAPP_AMT_GOODS_PRICE_SUM": "Previous Goods Price (Sum)",
    "PREVAPP_AMT_DOWN_PAYMENT_MEAN": "Previous Down Payment (Mean)",
    "PREVAPP_AMT_DOWN_PAYMENT_MAX": "Previous Down Payment (Max)",
    "PREVAPP_AMT_DOWN_PAYMENT_SUM": "Previous Down Payment (Sum)",
    "PREVAPP_RATE_DOWN_PAYMENT_MEAN": "Down Payment Rate (Mean)",
    "PREVAPP_RATE_DOWN_PAYMENT_MAX": "Down Payment Rate (Max)",
    "PREVAPP_DAYS_FIRST_DUE_MEAN": "Days to First Due (Mean)",
    "PREVAPP_DAYS_FIRST_DUE_MAX": "Days to First Due (Max)",
    "PREVAPP_DAYS_LAST_DUE_1ST_VERSION_MEAN": "Days to Last Due (Version 1) (Mean)",
    "PREVAPP_DAYS_LAST_DUE_1ST_VERSION_MAX": "Days to Last Due (Version 1) (Max)",
    "PREVAPP_DAYS_LAST_DUE_MEAN": "Days to Last Due (Mean)",
    "PREVAPP_DAYS_LAST_DUE_MAX": "Days to Last Due (Max)",
    "PREVAPP_DAYS_TERMINATION_MEAN": "Days to Termination (Mean)",
    "PREVAPP_DAYS_TERMINATION_MAX": "Days to Termination (Max)",
    "PREVAPP_HOUR_APPR_PROCESS_START_MEAN": "Application Start Hour (Mean)",
    "PREVAPP_HOUR_APPR_PROCESS_START_MAX": "Application Start Hour (Max)",
    "PREVAPP_CNT_PAYMENT_MEAN": "Planned Payment Count (Mean)",
    "PREVAPP_CNT_PAYMENT_MAX": "Planned Payment Count (Max)",
    "PREVAPP_SELLERPLACE_AREA_MEAN": "Seller Area (Mean)",
    "PREVAPP_SELLERPLACE_AREA_MAX": "Seller Area (Max)",
    "PREVAPP_NFLAG_INSURED_ON_APPROVAL_MEAN": "Insurance Flag on Approval (Mean)",
    # --- Regions, rating, population ---
    "REGION_POPULATION_RELATIVE": "Region Population Relative",
    "REGION_RATING_CLIENT": "Region Rating (Client)",
    "REGION_RATING_CLIENT_W_CITY": "Region Rating (With City)",
    "REG_CITY_NOT_LIVE_CITY": "Not Living in Registered City Flag",
    "REG_CITY_NOT_WORK_CITY": "Not Working in Registered City Flag",
    # --- Social circle counts ---
    "OBS_30_CNT_SOCIAL_CIRCLE": "Observed 30‑Day Social Contacts",
    "OBS_60_CNT_SOCIAL_CIRCLE": "Observed 60‑Day Social Contacts",
    "DEF_30_CNT_SOCIAL_CIRCLE": "Defaults in 30‑Day Social Circle",
    "DEF_60_CNT_SOCIAL_CIRCLE": "Defaults in 60‑Day Social Circle",
    # --- Bureau requests / credit bureau ---
    "AMT_REQ_CREDIT_BUREAU_YEAR": "Credit Bureau Requests (1 Year)",
    "AMT_REQ_CREDIT_BUREAU_QRT": "Credit Bureau Requests (Quarter)",
    "AMT_REQ_CREDIT_BUREAU_MON": "Credit Bureau Requests (1 Month)",
    # --- Building & property meta averages ---
    "TOTALAREA_MODE": "Total Area (Normalized)",
    "LIVINGAREA_AVG": "Living Area (Average)",
    "LIVINGAPARTMENTS_AVG": "Living Apartments Count (Avg)",
    "NONLIVINGAREA_AVG": "Non‑Living Area (Average)",
    "NONLIVINGAPARTMENTS_AVG": "Non‑Living Apartments Count (Avg)",
    "BASEMENTAREA_AVG": "Basement Area (Average)",
    "COMMONAREA_AVG": "Common Area (Average)",
    "COMMONAREA_MEDI": "Common Area (Median)",
    "COMMONAREA_MODE": "Common Area (Mode)",
    "LANDAREA_AVG": "Land Area (Average)",
    "FLOORSMAX_AVG": "Max Floors (Average)",
    "FLOORSMIN_AVG": "Min Floors (Average)",
    "ENTRANCES_AVG": "Entrances (Average)",
    "ELEVATORS_AVG": "Elevators (Average)",
    "YEARS_BEGINEXPLUATATION_AVG": "Years Since Exploitation Began (Avg)",
    "YEARS_BUILD_AVG": "Years Since Building (Avg)",
    # --- Credit type / reasons / reject codes ---
    "CREDIT_ACTIVE_Closed": "Credit Active – Closed",
    "CREDIT_ACTIVE_Active": "Credit Active – Active",
    "CREDIT_TYPE_Credit card": "Credit Type – Credit Card",
    "CREDIT_TYPE_Consumer credit": "Credit Type – Consumer Credit",
    "CREDIT_TYPE_Microloan": "Credit Type – Micro‑loan",
    "CODE_REJECT_REASON_XAP": "Reject Reason – XAP",
    "CODE_REJECT_REASON_HC": "Reject Reason – HC",
    "CODE_REJECT_REASON_LIMIT": "Reject Reason – Limit",
    "CODE_REJECT_REASON_SCO": "Reject Reason – Score (SCO)",
    "CODE_REJECT_REASON_SCOFR": "Reject Reason – Score (SCOFR)",
    # --- Misc IDs, flags, combos ---
    "SK_ID_CURR": "Customer ID",
    "PREVAPP_RATE_DOWN_PAYMENT_MEAN": "Down Payment Rate (Mean)",
    "PREVAPP_RATE_DOWN_PAYMENT_MAX": "Down Payment Rate (Max)",
}
import os

output_dir = "frontend/src"
os.makedirs(output_dir, exist_ok=True)

# Write the aliases to JSON
output_path = os.path.join(output_dir, "feature_aliases.json")
with open(output_path, "w") as f:
    json.dump(FEATURE_ALIASES, f, indent=2)

print(f"✅ Feature aliases exported to {output_path}")